config/routes.rb
Rails.application.routes.draw do

	resources :products
root 'products#index'

mount Products::ProductsAPI => '/api/products'

  get 'products/index'

  get 'products/show'

  get 'products/new'

  get 'products/create'

  get 'products/edit'

  get 'products/update'

  get 'products/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
validates :name, presence: true
validates :price, presence: true, numericality: {:greater_than => 0}
validates :short_description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 
  # GET method to get all products from database
  def index
    @products = Product.all
  end
 
  # GET method to get a product by id
  def show
    @product = Product.find(params[:id])
  end
 
  # GET method for the new product form
  def new
    @product = Product.new
  end
 
  # POST method for processing form data
  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Product added!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit product!'
      render :new
    end
  end
 
   # GET method for editing a product based on id
  def edit
    @product = Product.find(params[:id])
  end
 
  # PUT method for updating in database a product based on id
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = 'Product updated!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to edit product!'
      render :edit
    end
  end
 
  # DELETE method for deleting a product from database based on id
  def destroy
    @product = Product.find(params[:id])
    if @product.delete
      flash[:notice] = 'Product deleted!'
      redirect_to root_path
    else
      flash[:error] = 'Failed to delete this product!'
      render :destroy
    end
  end
 
  # we used strong parameters for the validation of params
  def product_params
    params.require(:product).permit(:name, :price, :old_price, :short_description, :full_description)
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css' %>
<%= stylesheet_link_tag    'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css' %>

  </head>

  <body>
   <div class="container">
<div><% if flash[:notice] %>
<div><%= flash[:notice] %></div>
<% end %> <%= yield %></div>
</div>
</div>

<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
<%= javascript_include_tag 'https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js' %>

  </body>
</html>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
  <div class="container">

  <%= form_for @product, url: {action: :update} do |f| %>
     
     <h3>Add a Product</h3>
	  <%= "<div>#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>
      <p>

       <div>
              <label>Product Name</label>
              <%= f.text_field :name %>
       </div>

       <div>
              <label>Price</label>
              <%= f.text_field :price %>
       </div>
        
       <div>
              <label>Description</label>
              <%= f.text_field :short_description %>
       </div>

        </p>
     <div>
        <%= link_to 'Back', { controller: 'products', action: 'index'} %>
        <%= f.submit 'Update Product' %>
      </div>
  <% end %>
</div>

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
<body bgcolor="red">
 <div class="container">
    <h3>STOCK LIST</h3>
   
      <div>
        <%= link_to 'Add Product', new_product_path %>
      </div>
      <br>
    <table border="2" id="heading">
      <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Actions</th>
      </tr>
      </thead>

<p style="color: pink">Total Number Of Products   : -- <%=  @products.count %></p>


      <tbody>
          <% @products.each do |product| %>

          <tr>

            <td><%= product.name %></td>
            <td><%= product.price %></td>
            <td><%= truncate(product.short_description, :length => 75) %></td>
               <div>
               <td>
                <%= link_to 'Show', product_path(product) %>
                <%= link_to 'Edit', edit_product_path(product) %>
                <%= link_to 'Delete', product_path(product), method: :delete %>
              </div>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    </div>
  </body>
</html>

app/views/products/new.html.erb
<div class="container">
  <%= form_for @product, url: {action: :create} do |f| %>
      <div>
        <h3>Add a Product</h3>
      </div>
      <div>
        <p>
          <%= "<div>#{@product.errors.full_messages.first}</div>".html_safe if @product.errors.any? %>
        <div>
            <label>Product Name</label>
              <%= f.text_field :name %>
        </div>

        <div>
             <label>Price</label>
             <%= f.text_field :price %>
        </div>

        <div>
           <label>Description</label>
              <%= f.text_field :short_description %>
        </div>
		 </p>
      </div>
      <div>
        <%= link_to 'Back', { controller: 'products', action: 'index'} %>
        <%= f.submit 'Create Product' %>
      </div>
  <% end %>
</div>

app/views/products/show.html.erb
 <div id="heading">      
        <h3>Add a Product</h3>
     
            <div>
              <label>Product Name</label>
              <%= @product.name %>
            </div>

            <div>
              <label>Price</label>
              <%= @product.price %>
            </div>
          
            <div>
              <label>Description</label>
              <%= @product.short_description %>
            </div>
       
      <div>
        <%= link_to 'Back', { controller: 'products', action: 'index'} %>
      </div>
</div>